### ISSUE TITLE
Downloads start but do not finish

### ISSUE THREAD

**Issue by araujoanderson** [UncleJunVIP/Mortar.pak#17]
Hello, 

First of all, thanks for such a handy tool.

The issue I'm seeing is that I get the roms lists from the megathread and the downloads start but they stop with the error: **"Unable to complete download for xx-rom.zip"**

I'm using the latest version of NextUI (just updated it today) and the Roms path is the default one.

Here's what the **Mortar log  says**(**the first part can be ignored as I shamefully didn't update the URL,** but afterwards then I see errors with trying to create a folder which I suppose it wouldn't need to since the Roms path is the default used on NextUI):

```
{"level":"error","timestamp":"2025-04-14T21:45:57.603-0400","msg":"Error downloading MortarItem List","error":"unable to fetch table:, Get \"https://firstruleoffight.club/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/\": dial tcp: lookup firstruleoffight.club on [::1]:53: read udp [::1]:58522->[::1]:53: read: connection refused"}
{"level":"error","timestamp":"2025-04-14T21:46:09.601-0400","msg":"Error downloading MortarItem List","error":"unable to fetch table:, Get \"https://firstruleoffight.club/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/\": dial tcp: lookup firstruleoffight.club on [::1]:53: read udp [::1]:59214->[::1]:53: read: connection refused"}
{"level":"error","timestamp":"2025-04-14T21:48:43.613-0400","msg":"Error downloading MortarItem List","error":"unable to fetch table:, Get \"https://firstruleoffight.club/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/\": dial tcp: lookup firstruleoffight.club on [::1]:53: read udp [::1]:43626->[::1]:53: read: connection refused"}
{"level":"error","timestamp":"2025-04-14T21:48:55.603-0400","msg":"Error downloading MortarItem List","error":"unable to fetch table:, Get \"https://firstruleoffight.club/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/\": dial tcp: lookup firstruleoffight.club on [::1]:53: read udp [::1]:45195->[::1]:53: read: connection refused"}
{"level":"error","timestamp":"2025-04-14T22:36:57.039-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:37:09.007-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:37:31.692-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:37:47.810-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:38:20.943-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:38:58.013-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}

```

And Here's how the **config.yml** file looks (pretty much the standard from the example just with the https://youknowwhat.secret added)
hosts:

 ```
 - display_name: "Fight Club"
    host_type: MEGATHREAD
    root_uri: "https://mmmmmm.me"

    sections:
      - section_name: "Game Boy"
        system_tag: "GB"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy/"
      - section_name: "Game Boy Color"
        system_tag: "GBC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/"
      - section_name: "Game Boy Advance"
        system_tag: "GBA"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/"
      - section_name: "Nintendo Entertainment System"
        system_tag: "FC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/"
      - section_name: "Super Nintendo Entertainment System"
        system_tag: "SFC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/"
      - section_name: "PlayStation"
        system_tag: "PS"
        host_subdirectory: "/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/"

    filters:
      - "USA"
      - "En,"

show_item_count: false
download_art: true
log_level: "ERROR"
```

_**P.S. While double reading this I found out the root_uri: what's set with a "/" at the end(  root_uri: "https://mmmmmm.me/"), I removed it and tried again and had the same result**_

I tried manually downloading one of the roms I had tried before and adding it to the SD card and I was able to do so, no issues, so it doesn't look to be a faulty card or anything similar.

Apologies If this is an error on my end (I wouldn't be surprised  if it was) but in case it wasn't I just wanted to provide what I believe could be valuable feedback.

**Comment by BrandonKowalski** [comment]
I'm currently working on an update that will correct some sins I committed early on in development. This may address the issue. If it doesn't, I'll be more than happy to help troubleshoot.

Thanks for the issue!

**Comment by araujoanderson** [comment]
> I'm currently working on an update that will correct some sins I committed early on in development. This may address the issue. If it doesn't, I'll be more than happy to help troubleshoot.
> 
> Thanks for the issue!

Thanks for the fast reply, if you need more info, please let me know so I can provide it.

**Comment by BrandonKowalski** [comment]
Give v.1.5.0 a shot.

If stuff is still broken, switch your logging level to DEBUG and relaunch Mortar. 

Perform actions until the issue occurs and then you can send me that log file.

**Comment by araujoanderson** [comment]
> Give v.1.5.0 a shot.
> 
> If stuff is still broken, switch your logging level to DEBUG and relaunch Mortar.
> 
> Perform actions until the issue occurs and then you can send me that log file.

Cool, I'll test it later and report back. Thanks for the quick response.

**Comment by araujoanderson** [comment]
Sadly after updating I still see the same issue, here's the log(I removed everything from the previous version):

```
{"level":"error","timestamp":"2025-04-15T11:24:35.935-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-15T11:25:27.593-0400","msg":"Error loading screen"}
{"level":"error","timestamp":"2025-04-15T11:25:31.587-0400","msg":"Error loading screen"}
{"level":"debug","timestamp":"2025-04-15T11:42:14.677-0400","msg":"Fetching Item List","AppState":{"config":{"hosts":[{"display_name":"Fight Club","host_type":"MEGATHREAD","root_uri":"https://myrient.erista.me","port":"0","extension_filters":"","sections":[{"name":"Game Boy","system_tag":"GB","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","romm_platform_id":""},{"name":"Game Boy Color","system_tag":"GBC","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/","romm_platform_id":""},{"name":"Game Boy Advance","system_tag":"GBA","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/","romm_platform_id":""},{"name":"Nintendo Entertainment System","system_tag":"FC","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/","romm_platform_id":""},{"name":"Super Nintendo Entertainment System","system_tag":"SFC","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/","romm_platform_id":""},{"name":"PlayStation","system_tag":"PS","local_directory":"","host_subdirectory":"/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/","romm_platform_id":""}],"table_columns":{"filename_header":"","file_size_header":"","date_header":""},"source_replacements":{},"section_indices":{}}],"show_item_count":false,"download_art":true,"art_download_type":"BOX_ART","log_level":"DEBUG"},"host":{"display_name":"Fight Club","host_type":"MEGATHREAD","root_uri":"https://myrient.erista.me","port":"0","extension_filters":"","sections":[{"name":"Game Boy","system_tag":"GB","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","romm_platform_id":""},{"name":"Game Boy Color","system_tag":"GBC","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/","romm_platform_id":""},{"name":"Game Boy Advance","system_tag":"GBA","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/","romm_platform_id":""},{"name":"Nintendo Entertainment System","system_tag":"FC","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/","romm_platform_id":""},{"name":"Super Nintendo Entertainment System","system_tag":"SFC","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/","romm_platform_id":""},{"name":"PlayStation","system_tag":"PS","local_directory":"","host_subdirectory":"/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/","romm_platform_id":""}],"table_columns":{"filename_header":"","file_size_header":"","date_header":""},"source_replacements":{},"section_indices":{"Game Boy":0,"Game Boy Color":1,"Game Boy Advance":2,"Nintendo Entertainment System":3,"Super Nintendo Entertainment System":4,"PlayStation":5}},"current_screen":"Loading","current_section":{"name":"Game Boy","system_tag":"GB","local_directory":"","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","romm_platform_id":""},"current_items_list":[],"search_filter":"","selected_file":"","last_saved_art_path":""}}
{"level":"debug","timestamp":"2025-04-15T11:42:25.340-0400","msg":"Downloading file...","remotePath":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","localPath":"","filename":"Addams Family, The (USA).zip","rename":""}
{"level":"error","timestamp":"2025-04-15T11:42:25.890-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-15T11:42:30.781-0400","msg":"Error loading screen"}
{"level":"error","timestamp":"2025-04-15T11:42:32.615-0400","msg":"Error loading screen"}
```
I see localpath seems to be empty( "localPath":"",") So I don't know if that's expected or not.

**Comment by BrandonKowalski** [comment]
Can you attach your config.yml?

**Comment by araujoanderson** [comment]
> Can you attach your config.yml?

Sure, here it is:

hosts:
  - display_name: "Fight Club"
    host_type: MEGATHREAD
    root_uri: "https://thatsiteyouknow.me"

    sections:
      - section_name: "Game Boy"
        system_tag: "GB"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy/"
      - section_name: "Game Boy Color"
        system_tag: "GBC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/"
      - section_name: "Game Boy Advance"
        system_tag: "GBA"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/"
      - section_name: "Nintendo Entertainment System"
        system_tag: "FC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/"
      - section_name: "Super Nintendo Entertainment System"
        system_tag: "SFC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/"
      - section_name: "PlayStation"
        system_tag: "PS"
        host_subdirectory: "/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/"

    filters:
      exclusive_filters:
        - "(Proto"
        - "(Demo)"
        - "(Beta)"
        - "(Aftermarket"
        - "4-in-1"
        - "4 in 1"
        - "(Europe)"
        - "(Japan)"
      inclusive_filters:
        - "USA"
        - "En,"

show_item_count: false
download_art: true
log_level: "DEBUG"

**Comment by JeromeGsq** [comment]
@BrandonKowalski Same issues. 
Mine is 'Sony PlayStation (PS)'

**Comment by BrandonKowalski** [comment]
@JeromeGsq You are running NextUI correct?

Do your logs show an empty local_directory as well?

**Comment by araujoanderson** [comment]
> I nuked my config and replaced it with yours and it worked without a hitch (Obviously fixing the `root_uri`).
> 
> I also deleted Mortar from my Brick and re-downloaded the 1.5.0 release and added your config in and that worked as well.
> 
> So I'm currently stumped.
> 
> Two more questions for ya:
> 
>     1. You are running NextUI correct? This has not been tested by me on anything other than NextUI.
> 
>     2. What does your `SDCARD_ROOT/Roms` directory listing look like? As you know it uses the Tag in the folder names to bind the directories.
> 
> 
> For example my `SDCARD_ROOT/Roms` looks like this:
> 
> ```
> 1) Game Boy (GB)
> 2) Game Boy Color (GBC)
> 3) Game Boy Advance (GBA)
> 4) Nintendo Entertainment System (FC)
> 5) Super Nintendo Entertainment System (SFC)
> 6) PlayStation (PS)
> ```
> 
> I also just tried it removing the leading sorting numbers I use (e.g. `3)`) and that also worked.



Yes I'm using NextUI and this is what SDCARD_Root/Roms  looks like:

![Image](https://github.com/user-attachments/assets/546ceb0c-ef41-407d-a223-9861314b98dd)

**Comment by JeromeGsq** [comment]
Yes, NextUI, latest version.
My logs:

```
{"level":"debug","timestamp":"2025-04-15T20:46:45.005+0200","msg":"Fetching Item List","AppState":{"config":{"hosts":[{"display_name":"myrient","host_type":"MEGATHREAD","root_uri":"https://x.x.x","port":"0","extension_filters":"","sections":[{"name":"Game Boy","system_tag":"GB","local_directory":"/mnt/SDCARD/Roms/Game Boy (GB)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","romm_platform_id":""},{"name":"Game Boy Color","system_tag":"GBC","local_directory":"/mnt/SDCARD/Roms/Game Boy Color (GBC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/","romm_platform_id":""},{"name":"Game Boy Advance","system_tag":"GBA","local_directory":"/mnt/SDCARD/Roms/Game Boy Advance (GBA)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/","romm_platform_id":""},{"name":"Nintendo Entertainment System","system_tag":"FC","local_directory":"/mnt/SDCARD/Roms/Nintendo Entertainment System (FC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/","romm_platform_id":""},{"name":"Super Nintendo Entertainment System","system_tag":"SFC","local_directory":"/mnt/SDCARD/Roms/Super Nintendo Entertainment System (SFC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/","romm_platform_id":""},{"name":"PlayStation","system_tag":"PS","local_directory":"/mnt/SDCARD/Roms/PlayStation (PS)","host_subdirectory":"/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/","romm_platform_id":""}],"table_columns":{"filename_header":"","file_size_header":"","date_header":""},"source_replacements":{},"section_indices":{}}],"show_item_count":false,"download_art":false,"art_download_type":"BOX_ART","log_level":"DEBUG"},"host":{"display_name":"myrient","host_type":"MEGATHREAD","root_uri":"https://x.x.x","port":"0","extension_filters":"","sections":[{"name":"Game Boy","system_tag":"GB","local_directory":"/mnt/SDCARD/Roms/Game Boy (GB)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","romm_platform_id":""},{"name":"Game Boy Color","system_tag":"GBC","local_directory":"/mnt/SDCARD/Roms/Game Boy Color (GBC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/","romm_platform_id":""},{"name":"Game Boy Advance","system_tag":"GBA","local_directory":"/mnt/SDCARD/Roms/Game Boy Advance (GBA)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/","romm_platform_id":""},{"name":"Nintendo Entertainment System","system_tag":"FC","local_directory":"/mnt/SDCARD/Roms/Nintendo Entertainment System (FC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/","romm_platform_id":""},{"name":"Super Nintendo Entertainment System","system_tag":"SFC","local_directory":"/mnt/SDCARD/Roms/Super Nintendo Entertainment System (SFC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/","romm_platform_id":""},{"name":"PlayStation","system_tag":"PS","local_directory":"/mnt/SDCARD/Roms/PlayStation (PS)","host_subdirectory":"/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/","romm_platform_id":""}],"table_columns":{"filename_header":"","file_size_header":"","date_header":""},"source_replacements":{},"section_indices":{"Game Boy":0,"Game Boy Color":1,"Game Boy Advance":2,"Nintendo Entertainment System":3,"Super Nintendo Entertainment System":4,"PlayStation":5}},"current_screen":"Loading","current_section":{"name":"Game Boy","system_tag":"GB","local_directory":"/mnt/SDCARD/Roms/Game Boy (GB)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","romm_platform_id":""},"current_items_list":[],"search_filter":"","selected_file":"","last_saved_art_path":""}}
{"level":"error","timestamp":"2025-04-15T20:46:45.023+0200","msg":"Error downloading Item List","error":"unable to fetch table:, Get \"https://x.x.x/files/No-Intro/Nintendo%20-%20Game%20Boy/\": dial tcp: lookup x.x.x on [::1]:53: read udp [::1]:35093->[::1]:53: read: connection refused"}
{"level":"error","timestamp":"2025-04-15T20:47:15.019+0200","msg":"Error loading screen"}
{"level":"debug","timestamp":"2025-04-15T20:49:17.250+0200","msg":"Fetching Item List","AppState":{"config":{"hosts":[{"display_name":"myrient","host_type":"MEGATHREAD","root_uri":"https://x.x.x","port":"0","extension_filters":"","sections":[{"name":"Game Boy","system_tag":"GB","local_directory":"/mnt/SDCARD/Roms/Game Boy (GB)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","romm_platform_id":""},{"name":"Game Boy Color","system_tag":"GBC","local_directory":"/mnt/SDCARD/Roms/Game Boy Color (GBC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/","romm_platform_id":""},{"name":"Game Boy Advance","system_tag":"GBA","local_directory":"/mnt/SDCARD/Roms/Game Boy Advance (GBA)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/","romm_platform_id":""},{"name":"Nintendo Entertainment System","system_tag":"FC","local_directory":"/mnt/SDCARD/Roms/Nintendo Entertainment System (FC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/","romm_platform_id":""},{"name":"Super Nintendo Entertainment System","system_tag":"SFC","local_directory":"/mnt/SDCARD/Roms/Super Nintendo Entertainment System (SFC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/","romm_platform_id":""},{"name":"PlayStation","system_tag":"PS","local_directory":"/mnt/SDCARD/Roms/PlayStation (PS)","host_subdirectory":"/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/","romm_platform_id":""}],"table_columns":{"filename_header":"","file_size_header":"","date_header":""},"source_replacements":{},"section_indices":{}}],"show_item_count":false,"download_art":false,"art_download_type":"BOX_ART","log_level":"DEBUG"},"host":{"display_name":"myrient","host_type":"MEGATHREAD","root_uri":"https://x.x.x","port":"0","extension_filters":"","sections":[{"name":"Game Boy","system_tag":"GB","local_directory":"/mnt/SDCARD/Roms/Game Boy (GB)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","romm_platform_id":""},{"name":"Game Boy Color","system_tag":"GBC","local_directory":"/mnt/SDCARD/Roms/Game Boy Color (GBC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/","romm_platform_id":""},{"name":"Game Boy Advance","system_tag":"GBA","local_directory":"/mnt/SDCARD/Roms/Game Boy Advance (GBA)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/","romm_platform_id":""},{"name":"Nintendo Entertainment System","system_tag":"FC","local_directory":"/mnt/SDCARD/Roms/Nintendo Entertainment System (FC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/","romm_platform_id":""},{"name":"Super Nintendo Entertainment System","system_tag":"SFC","local_directory":"/mnt/SDCARD/Roms/Super Nintendo Entertainment System (SFC)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/","romm_platform_id":""},{"name":"PlayStation","system_tag":"PS","local_directory":"/mnt/SDCARD/Roms/PlayStation (PS)","host_subdirectory":"/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/","romm_platform_id":""}],"table_columns":{"filename_header":"","file_size_header":"","date_header":""},"source_replacements":{},"section_indices":{"PlayStation":5,"Game Boy":0,"Game Boy Color":1,"Game Boy Advance":2,"Nintendo Entertainment System":3,"Super Nintendo Entertainment System":4}},"current_screen":"Loading","current_section":{"name":"Game Boy","system_tag":"GB","local_directory":"/mnt/SDCARD/Roms/Game Boy (GB)","host_subdirectory":"/files/No-Intro/Nintendo%20-%20Game%20Boy/","romm_platform_id":""},"current_items_list":[],"search_filter":"","selected_file":"","last_saved_art_path":""}}
{"level":"error","timestamp":"2025-04-15T20:49:47.263+0200","msg":"Error downloading Item List","error":"unable to fetch table:, Get \"https://x.x.x/files/No-Intro/Nintendo%20-%20Game%20Boy/\": dial tcp 31.7.57.122:443: i/o timeout"}
{"level":"error","timestamp":"2025-04-15T20:49:53.759+0200","msg":"Error loading screen"}
```

**Comment by araujoanderson** [comment]
> > I nuked my config and replaced it with yours and it worked without a hitch (Obviously fixing the `root_uri`).
> > I also deleted Mortar from my Brick and re-downloaded the 1.5.0 release and added your config in and that worked as well.
> > So I'm currently stumped.
> > Two more questions for ya:
> > ```
> > 1. You are running NextUI correct? This has not been tested by me on anything other than NextUI.
> > 
> > 2. What does your `SDCARD_ROOT/Roms` directory listing look like? As you know it uses the Tag in the folder names to bind the directories.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For example my `SDCARD_ROOT/Roms` looks like this:
> > ```
> > 1) Game Boy (GB)
> > 2) Game Boy Color (GBC)
> > 3) Game Boy Advance (GBA)
> > 4) Nintendo Entertainment System (FC)
> > 5) Super Nintendo Entertainment System (SFC)
> > 6) PlayStation (PS)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also just tried it removing the leading sorting numbers I use (e.g. `3)`) and that also worked.
> 
> Yes I'm using NextUI and this is what SDCARD_Root/Roms looks like:
> 
> ![Image](https://github.com/user-attachments/assets/546ceb0c-ef41-407d-a223-9861314b98dd)
> 
> on your reply when you say something like: Game Boy Advance (GBA) the full text is expected to be the name of the folder? or just GBA?

From @jeromeGsq logs I can see I actually need to have the folders named something like: Game Boy Advance (GBA) instead of just GBA or something like that, I wonder if this was due to me getting one of the compiled roms packs that are out there, perhaps I configured manually the roms paths for NextUI to find the roms there in the non default paths and I forgot I did(is that something NextUI allows to do?)

As suspected, this one looks to be on me, Apologies. I think I will use hardcoded paths on my config.yml(if that's still allowed) so I don't have to rename the current  folders under SDCARD_ROOT/Roms and risk having whatever NextUI config I have throw a fit.

**Comment by BrandonKowalski** [comment]
@araujoanderson yeah since you are using non-standard naming for the folders Mortar cannot automagically find your stuff. It should work with the hardcoded directories like you said. 

Just remember to remove system_tag cause that option will take priority.

**Comment by araujoanderson** [comment]
> [@araujoanderson](https://github.com/araujoanderson) yeah since you are using non-standard naming for the folders Mortar cannot automagically find your stuff. It should work with the hardcoded directories like you said.
> 
> Just remember to remove system_tag cause that option will take priority.
> 
> For reference here is the standard naming in the docs: https://nextui.loveretro.games/getting-started/roms/

Thanks for the naming conventions doc, I will try to simply add the tag to my current folder names and hopefully that would Allow mortar to find them without me having to add the hardcoded full paths, one question just to confirm, if I have a folder called GBA and I rename it to something like GBA(GBA) would that work? or I need to go full Game Boy Advance (GBA)?

**Comment by JeromeGsq** [comment]
> [@JeromeGsq](https://github.com/JeromeGsq) so you have a local directory being picked up. I suspect you are not connected to Wi-Fi.
> 
> There is currently an issue in NextUI where the Wi-Fi icon will show in the top right but you are not actually connected. Please verify you are connected by visiting the Wi-Fi section in settings.

Ok it works. Thx!

**Comment by araujoanderson** [comment]
> [@araujoanderson](https://github.com/araujoanderson) You can keep the display name as is. I would recommend naming it `GBA (GBA)` with the space between the display name and tag.
> 
> Also the tag isn't just for show it is how NextUI binds to the emulator.

Thanks, I added the tag to a few to test and it is working now as expected. Sorry  and thanks for your time. I Learned something new today. (I still wonder how were my games showing up at all on NextUI before, I even have art imgs and everything... )

**Comment by BrandonKowalski** [comment]
@araujoanderson Enjoy!
